---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - operators

  - ns-istio-system.yaml
  - smcp-basic.yaml
  - smmr-default.yaml
  - telemetry-mesh-default.yaml

  - ossmconsole.yaml
